Add Hatch configuration. (#2884)
* Development version

* Fix bad selection of items in Project Explorer with Right Click.

* Simplify execution with .exe. Removed main panel scrollbars at Grid Editor

* update package w/ to solve upgrade rom dev

* update docs

* Improve restoring of preferences/configobj when upgrade from development

* Add syntax colorization for GROUP marker. Improve Gherking recognition for multiple words.

* Improve localized Gherkin in Grid Editor

* Improve Gherkin recognition for localized docs in autocomplete

* Create directory in New Project dialog, if needed.

* Update README.adoc

* Add tab marker lines to Text Editor. Ongoing collapse/expand blocks.

* Add folding markers in Text Editor

* Fix colors of line numbers in Text Editor, add folding and tab markers

* Fix broken Code Editor launch

* Fix text color in row labels in Grid Editor

* First increment in autocomplete Text Editor, breaks Editor.

* Improve autocomplete in Editor

* Remove details fo str in Editor, improve autocomplete list TextEditor

* Better but slower autocomplete list TextEditor

* DEBUG get_suggestions, returning many non matching words

* More debuggings on TextEditor

* Fixed matchin list on TextEditor

* Increase unit tests

* Improve autocomplete lists

* DOCS: -
fix an incorrect link redirect to the slack robotframework community
- add the 'commit' command on the instruction 7 on how to contribute.

* Fix missing double-quote

* Downgrade setuptools on Debian

* Downgrade setuptools on Debian

* Set SonarQube project version to 2.1.3

* fix: AttributeError: 'NoneType' object has no attribute 'name' #2928

* Set version.py to development

* Update README.adoc

* Update releasenotes.py

* New status bar and PoC in Text Editor

* Debug eventwatcher

* Improve filesystem changes when opening project on Windows

* Update docs.

* Fix texteditor unit test

* Add protection for language selection

* Add Control Panel to Plugins. First example on Text Editor

* Set config_panel to be bitmap button in Text Editor

* Add settings button to Plugins Manager (not OK)

* Fix language detection error

* Add Config Panel button to Plugins Manager on supported plugins

* Add unit tests for mainframe

* Improve status_bar clear. Try to force status_ba color

* Experimental code for Python 3.8 no RF installed

* Make RIDE working without Robot Framework or version older than 6.0

* Added current executing keyword and other statuses to TestRunner status bar

* Added Settings button to Test Runner

* Change proportion in StatusBar 40/60

* Change Message box to RIDEDialog (#2936)

* Styled message box

* More dialogs with style. Broken validation on New Projects

* Fix dialogs colour in main and filedialog

* Fix dialogs colour in ProgressDialogs

* Change dialogs to use customized colors

* Change dialogs to use customized colors in Treenodehandlers

* Change dialogs to use customized colors in Tagdialogs

* Change dialogs to use customized colors in Logger

* Change dialogs to use customized colors in Run/ui

* Change dialogs to use customized colors in specimporter

* Change dialogs to use customized colors in testrunner

* Final change dialogs to use customized colors

* Initial settings edit button on Preferences. Make backup of settings.cfg

* Settings editor button at Preferences and backup of settings.cfg

* Add unit tests for Preferences panel. WIP

* Edit proper settings file. Add protection on create settings backup (#2938)

* Increases Python supported version (#2939)

* Increases maximum supported Python version, for Python 3.14 future versions.

* Corrects title in Code Editor when opening file.

* Add Fedora 41 with wxPython 4.2.3 on Python 3.14 and save coverage-report (#2940)

* Add configuration for Fedora-41 with Python 3.14 in venv and wxPython 4.2.3

* Separate configuration for Fedora 41 with Python 3.14 in venv with wxPython 4.2.3

* Modify order of commands in Fedora Py314

* Activate venv in Fedora Py314

* Install psmisc in Fedora Py314 to provide killall

* Install robotframework. Save coverage-report

* Save coverage-report, also on Debian

* Save coverage-report, removed name

* Save coverage-report, removed slash

* Save coverage-report in a zip archive

* Save coverage-report FIX identation

* Save coverage-report removed name

* Save coverage-report install zip

* Not using zip to get coverage-reports (#2941)

* Improve tests on Windows (#2942)

* Improve utests (#2943)

* Improve utests

* Update utests. Keep coverage.xml

* Update fedora_41.yml

* Update linux.yml

* Improve utests (#2944)

* Improve application utest

* Collect coverage-reports

* Improve coverage-reports (#2945)

* Save coverage-report xml

* Add contexts to coverage report

* Update AppVeyor config for coverage-reports

* Save SQL-Lite from coverage-repoorts

* Save SQL-Lite from coverage-repoorts, another try

* Save SQL-Lite from coverage-reports, add option to include hidden files

* Fix blank squares in Tree and avoid crashing when execution is too rapid (#2947)

* Fixes missing context menu in Grid Editor (#2948)

* Minor code improvements (#2949)

* Unit test for widgets.HtmlWindow

* Improve unit tests on MacOS

* Unit test for widgets.HtmlWindow

* Improve unit tests on MacOS

* Attempt to cover branch in test_htmlwindow. WIP

* Improve two 100% tests

* Debug test_htmlwnd

* Increase low coverage

* Add fs_watcher test

* Omit non tested files from coverage

* Add DEBUG to Grid. Improve kwedito tests

* Minor fixes in utests

* Improve Grid tests WIP debug failed tests

* Improve RF version detection

* Exclude files from coverage. Grid tests fail in shell not IDE

* Fixes missing context menu in Grid Editor (#2948)

* Minor code improvements

---------

* Add Hatch configuration. Command line arguments are not working, i.e. ride --version

* Update versions in pyproject.toml

---------

Co-authored-by: Wellington <wellingtonasilva45@gmail.com>
Co-authored-by: Shao Yu-Lung (Allen) <bestlong168@gmail.com>